In [1]:
import numpy as np

# Example 2D array of shape (6, 6)
arr = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36]
])

# Extract a 2x2 sub-array starting from position (1, 1)
sub_array = arr[1:3, 1:3]

print(sub_array)

[[ 8  9]
 [14 15]]


In [2]:
# Form a 3D array of shape (3, 2, 1)
arr = np.array([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])

extracted_elements = arr[:2, :, 0]

print(extracted_elements)

[[1 2]
 [3 4]]


In [3]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Extract elements at positions [1, 3, 4, 6]
extracted_elements = arr[[1, 3, 4, 6]]

print(extracted_elements)

[20 40 50 70]


In [4]:
#Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Use fancy indexing to select rows [0, 2, 2] and columns [1, 3]
rows = [0, 2, 2]
cols = [1, 3]

# Extract the elements using numpy's indexing
extracted_elements = arr[rows, :][:, cols]

print(extracted_elements)


[[ 2  4]
 [10 12]
 [10 12]]


In [5]:
#From a 1D array of random integers, extract all elements that are greater than 8.

arr = np.random.randint(1, 20, size=10)
extracted_elements = arr[arr > 8]

print("Array:", arr)
print("Elements greater than 8:", extracted_elements)

Array: [19  2  4  7 12 14 15 18  6  8]
Elements greater than 8: [19 12 14 15 18]


In [6]:
#Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.
# Example 2D array of shape (6, 6)
arr = np.array([
    [1, 2, 3, 14, 5, 16],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36]
])

# Replace all elements greater than 13 with 0
arr[arr > 13] = 0

print(arr)

[[ 1  2  3  0  5  0]
 [ 7  8  9 10 11 12]
 [13  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


BROADCASTING

In [7]:
arr1 = np.array([1, 2, 3])

# 2D array of shape (4, 3)
arr2 = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])

# Add the 1D array to each row of the 2D array
result = arr2 + arr1

print(result)

[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]
 [14 16 18]]


In [8]:
# 1D array of shape (3,)
arr1 = np.array([1, 2, 3])

# 2D array of shape (3, 3)
arr2 = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

# Multiply the 2D array by the 1D array
result = arr2 * arr1

print(result)

[[ 4 10 18]
 [ 7 16 27]
 [10 22 36]]


In [9]:
#Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.
arr1 = np.array([[1], [2], [3]])

# Create a 2D array of shape (1, 4)
arr2 = np.array([[4, 5, 6, 7]])

# Perform element-wise addition using broadcasting
result = arr1 + arr2

print(result)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


In [10]:
#Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.
# Create a 3D array of shape (2, 3, 4)
arr3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

# Create a 2D array of shape (3, 4)
arr2d = np.array([
    [1, 2, 1, 2],
    [3, 4, 3, 4],
    [5, 6, 5, 6]
])

# Add the 2D array to each 2D slice along the first axis
result = arr3d + arr2d

print(result)

[[[ 2  4  4  6]
  [ 8 10 10 12]
  [14 16 16 18]]

 [[14 16 16 18]
  [20 22 22 24]
  [26 28 28 30]]]


In [11]:
#Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.
# Example 2D array
arr2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

# Extract every second row and every second column
sliced_array = arr2d[::2, ::2]

print("Sliced Array:")
print(sliced_array)

# Example 1D array to add to each row of the sliced array
add_array = np.array([10, 20, 30, 40])

# Add the 1D array to each row of the sliced array
result = sliced_array + add_array[:, np.newaxis]

print("\nResult after adding 1D array to each row:")
print(result)

Sliced Array:
[[ 1  3  5]
 [11 13 15]]


ValueError: operands could not be broadcast together with shapes (2,3) (4,1) 