In [3]:
import numpy as np


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [13]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [15]:
# learned it from chatgpt it can be optimised asw 
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
arr = np.random.randint(1, 21, size=(3, 3))

In [30]:
print(arr)

[[ 8 11 17]
 [ 5 18  1]
 [18  3  2]]


In [31]:
#Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.

arr = np.array[(1,1),(1,1,1),(1,1,1,1)]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [32]:
arr = np.ones((2, 3, 4))

In [33]:
print(arr)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [35]:
#Add two 1D arrays element-wise.

arr = np.array([1,2,3])
arr1 = np.array([3,2,1])


In [36]:
print(arr + arr1)


[4 4 4]


In [37]:
#Multiply two 2D arrays element-wise.
print(arr * arr1)


[3 4 3]


In [39]:
#Calculate the dot product of two matrices.
dotprod = np.dot(arr,arr1)

In [40]:
print(dotprod)

10


In [45]:
#Calculate the mean, median, and standard deviation of a 1D array.

meanArr = np.mean(arr)
medianArr = np.median(arr)
sdArr = np.std(arr)

In [46]:
print(meanArr)
print(medianArr)
print(sdArr)

2.0
2.0
0.816496580927726


In [49]:
#Find the maximum and minimum values in a 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(arr1))
print(np.max(arr1))

1
6


In [50]:
#Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.
arr = np.random.normal(0, 1, 1000)
print(arr)

[ 3.58033136e-01 -4.07898556e-01 -9.55777956e-01  1.08204894e-01
 -2.04815095e-01 -5.28395080e-01 -1.05977961e+00 -9.08842284e-01
 -9.12667024e-02  1.06824182e+00  1.31796511e+00 -1.16618195e+00
 -2.48645351e-01  2.33361630e-01  9.32343969e-01  2.11150335e-01
  1.26854233e-01 -1.00095053e+00 -1.42845164e-01  2.07144653e-01
  3.86388849e-01  1.18816126e+00  1.22694414e+00  1.28796095e+00
 -2.85017528e-01 -2.18688370e+00  3.70499473e-01  1.63219136e-01
 -1.87283915e-01  3.81306662e+00 -8.33318557e-01 -7.54840530e-01
 -1.05469593e+00 -7.50277523e-01  5.43519016e-01  3.93072724e-01
 -1.17163888e+00 -1.16762226e+00 -8.02813728e-01  9.39838448e-01
 -4.34833068e-01  1.17601378e+00 -2.08840348e+00 -8.62921484e-01
 -3.03401713e-01 -1.19506674e+00  2.88207766e-01 -1.63164730e-01
 -4.29024957e-01 -8.94433241e-02  7.46647829e-01 -3.86681082e-01
 -2.22205070e-01  4.96841207e-01 -8.07447697e-01 -1.42536892e+00
  1.11054472e+00  1.36961883e+00  2.39935817e-01  2.91458291e-01
 -8.86104273e-01  1.30211

In [57]:
#Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.
arr = np.random.randint(10, 51, size=(5, 5))
print(arr)

[[13 40 25 10 21]
 [15 50 34 50 29]
 [45 27 14 45 11]
 [47 33 15 36 11]
 [35 47 22 21 12]]


In [4]:
#Calculate the cumulative sum of a 1D array.
arr = np.array([1, 3, 5, 7, 9])
cumulative_sum = np.cumsum(arr)
print(cumulative_sum)



[ 1  4  9 16 25]


In [5]:
# Compute the correlation coefficient matrix of a 2D array.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
correlation_matrix = np.corrcoef(arr)
print(correlation_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# Simulate rolling a six-sided die 1000 times
rolls = np.random.randint(1, 7, size=1000)
outcomes, counts = np.unique(rolls, return_counts=True)
frequency = dict(zip(outcomes, counts))
print(frequency)

{1: 186, 2: 175, 3: 174, 4: 146, 5: 180, 6: 139}
